baseURL = 'https://cloudnugget.dev/'
locale = 'en-us'
title = 'CloudNugget'
theme = 'hugo-book'

[params.sidebar]
showLevel = 1  # 1 = seulement les sections de premier niveau

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true